---
title: "descriptive analysis"
author: "최지우"
date: "4/16/2021"
output: html_document
---
```{r include=F}
knitr::opts_chunk$set(echo = T, message = F, warning = F, fig.align='center')
options(scipen = 1000)
```
# 기술 통계

## 데이터 불러오기

```{r}
library(tidyverse)
library(ggpubr)
library(kableExtra)
library(data.table)
library(RColorBrewer)

font <- "NanumGothic"

afterCovid<-read_csv("data/after_covid_petition.csv")
beforeCovid<-read_csv("data/before_covid_petition.csv")
category <- unique(afterCovid$category)
```

## 함수 정의

```{r}
# top 5 청원을 보여주는 함수
displayTop5 <- function(df, cap){
  df %>% 
    arrange(desc(numOfAgrees)) %>% 
    top_n(5) %>% 
    kbl(caption=cap) %>% 
    kable_styling
}
```

## 전체 Top 5 청원

```{r}
# 코로나 이전 청원 Top 5
displayTop5(beforeCovid, "코로나 이전 청원 Top 5")

# 코로나 이후 청원 Top 5
displayTop5(afterCovid, "코로나 이후 청원 Top 5")
```

## 코로나 이전과 이후 카테고리별 비율 (final 보고서에 추가 할지 말지 정하기)

```{r}
b4Ratio <- beforeCovid %>% 
            group_by(category) %>% 
              summarise(freq = n()) %>% 
                mutate(ratio = round(freq / sum(freq),4)*100)
acRatio <- afterCovid %>% 
            group_by(category) %>% 
              summarise(freq = n()) %>% 
                mutate(ratio = round(freq / sum(freq),4)*100)

acBcRatio <- bind_cols(category, b4Ratio$ratio, acRatio$ratio)
colnames(acBcRatio) <- c("category","before","after")
acBcRatioLong <- pivot_longer(acBcRatio,cols = 2:3, names_to = "period", values_to = "ratio")
acBcRatioLong$period <- factor(acBcRatioLong$period, levels=c("before","after"), order = T)

acBcRatioLong %>% ggbarplot("category", "ratio",
                          fill = "period", 
                          color = "period",
                          xlab = "",
                          ylab = "",
                          palette = "Paired",
                          position = position_dodge(0.9)) %>% 
                ggpar(x.text.angle = 45, font.family=font) %>% 
                  annotate_figure(top=text_grob("코로나 이전과 이후 카테고리별 비율", face="bold", family=font, size=16))
```

## 청원 카테고리별 동의를 10만 이상 받은 청원 건수 (final 보고서에 추가 할지 말지 정하기)

```{r}
# 청원동의수가 10만 이상 추출
bcOver100k <- beforeCovid[which(beforeCovid$numOfAgrees>=100000),]
acOver100k <- afterCovid[which(afterCovid$numOfAgrees>=100000),]

# 청원동의 10만 이상 카테고리 빈도수 -> 이거 비율로 해야되나?
bcCategoryFreq <- count(bcOver100k, category, sort = T)
acCategoryFreq <- count(acOver100k, category, sort = T)
category <- as.data.table(category)
acBcCat <- left_join(category,bcCategoryFreq) %>% left_join(acCategoryFreq, by='category')
acBcCat[is.na(acBcCat)] <- 0
colnames(acBcCat) <- c("category","bcCategory","acCategory")

# 그래프 그리기 위한 데이터프레임 설정
acBcCatLong <- pivot_longer(acBcCat,cols = 2:3, names_to = "period", values_to = "freq")
acBcCatLong$period <- factor(acBcCatLong$period, levels=c("bcCategory","acCategory"), order = T)
acBcCatLong$period

# 그래프
acBcCatLong %>% ggbarplot("category", "freq",
                          fill = "period", 
                          color = "period",
                          xlab = "",
                          ylab = "",
                          palette = "Paired",
                          position = position_dodge(0.9)) %>% 
                ggpar(x.text.angle = 45, font.family=font) %>% 
                  annotate_figure(top=text_grob("청원동의 10만 이상 카테고리별 청원 건수", face="bold", family=font, size=16))
```

## 코로나 이전 이후 상위 5개 카테고리 (final 보고서에 추가 할지 말지 정하기)

### 청원 개수별

```{r fig.width=16, fig.height=7}
# 청원 개수, 비율
bcNumPetitionRatio <- beforeCovid %>% 
  group_by(category) %>% 
  summarise(count=n()) %>% 
  arrange(desc(count)) %>%
  head(5) %>% 
  mutate(ratio=count/sum(count))
# 카테고리에 factor 부여하여 순서를 나타냄
bcNumPetitionRatio$category <- bcNumPetitionRatio$category %>% factor(levels = bcNumPetitionRatio$category)

acNumPetitionRatio <- afterCovid %>% 
  group_by(category) %>% 
  summarise(count=n()) %>% 
  arrange(desc(count)) %>%
  head(5) %>% 
  mutate(ratio=count/sum(count))
acNumPetitionRatio$category <- acNumPetitionRatio$category %>% factor(levels = acNumPetitionRatio$category)

# Bar
fig1 <- bcNumPetitionRatio %>% ggbarplot("category", "count",
                                    xlab = "before covid19",
                                    ylab = "",
                                    fill = "#0080ff",
                                    color = "#0080ff") %>% 
                               ggpar(x.text.angle = 45,
                                    font.family=font)

fig2 <- acNumPetitionRatio %>% ggbarplot("category", "count",
                                    xlab = "after covid19",
                                    ylab = "",
                                    fill = "#0080ff",
                                    color = "#0080ff") %>% 
                               ggpar(x.text.angle = 45,
                                    font.family=font)

ggarrange(fig1, fig2) %>% 
  annotate_figure(top=text_grob("코로나 전후 청원 건수 상위 5개 카테고리", face="bold", family=font, size=24))

# Pie
ratio <- paste0(bcNumPetitionRatio$category, "\n","(",round(bcNumPetitionRatio$ratio,4)*100, "%",")")
fig3 <- bcNumPetitionRatio %>% ggpie("ratio", 
                                     label = ratio, 
                                     fill = "category", 
                                     font.family = font,
                                     color = "white",
                                     lab.pos ="in",
                                     lab.font = c("black"),
                                     palette = c("#33cc33", "#b2e561", "#feffa2", "#fbe160", "#ffbf00")) +
                               theme(legend.text= element_text(size=12), legend.position = "left",legend.direction = "vertical")

ratio <- paste0(acNumPetitionRatio$category, "\n","(",round(acNumPetitionRatio$ratio,4)*100, "%",")")
fig4 <- acNumPetitionRatio %>% ggpie("ratio", 
                                     label = ratio, 
                                     fill = "category", 
                                     font.family = font,
                                     color = "white",
                                     lab.pos ="in",
                                     lab.font = c("black"), 
                                     palette = c("#00bfff", "#33e2f6", "#92ffe4", "#adec7d", "#ffbf00")) +
                               theme(legend.text= element_text(size=12), legend.position = "right",legend.direction = "vertical")

ggarrange(fig3, fig4, labels = c("before covid 19", "after covid 19"), hjust = c(-2.9,-2.1), vjust = 3) %>% 
  annotate_figure(top=text_grob("코로나 전후 청원 건수 상위 5개 카테고리 비율", face="bold", family=font, size=24))
```

### 청원 참여인원수별

```{r fig.width=16, fig.height=7}
bcNumAgreesRatio <- beforeCovid %>% 
  group_by(category) %>% 
  summarise(sum=sum(numOfAgrees)) %>% 
  arrange(desc(sum)) %>%
  head(5) %>% 
  mutate(ratio=sum/sum(sum))
bcNumAgreesRatio$category <- bcNumAgreesRatio$category %>% factor(levels = bcNumAgreesRatio$category)

acNumAgreesRatio <- afterCovid %>% 
  group_by(category) %>% 
  summarise(sum=sum(numOfAgrees)) %>% 
  arrange(desc(sum)) %>%
  head(5) %>% 
  mutate(ratio=sum/sum(sum))
acNumAgreesRatio$category <- acNumAgreesRatio$category %>% factor(levels = acNumAgreesRatio$category)

# Bar
fig1 <- bcNumAgreesRatio %>% ggbarplot("category", "sum",
                                    xlab = "before covid19",
                                    ylab = "",
                                    fill = "#0080ff",
                                    color = "#0080ff") %>% 
                               ggpar(x.text.angle = 45,
                                    font.family=font)

fig2 <- acNumAgreesRatio %>% ggbarplot("category", "sum",
                                    xlab = "after covid19",
                                    ylab = "",
                                    fill = "#0080ff",
                                    color = "#0080ff") %>% 
                               ggpar(x.text.angle = 45,
                                    font.family=font)

ggarrange(fig1, fig2) %>% 
  annotate_figure(top=text_grob("코로나 전후 청원 참여인원수 상위 5개 카테고리", face="bold", family=font, size=24))

# Pie
ratio <- paste0(bcNumAgreesRatio$category, "\n","(",round(bcNumAgreesRatio$ratio,4)*100, "%",")")
fig3 <- bcNumAgreesRatio %>% ggpie("ratio", 
                                     label = ratio, 
                                     fill = "category", 
                                     font.family = font,
                                     color = "white",
                                     lab.pos ="in",
                                     lab.font = c("black"),
                                     palette = c("#33cc33", "#b2e561", "#feffa2", "#fbe160", "#ffbf00")) +
                               theme(legend.text= element_text(size=12), legend.position = "left",legend.direction = "vertical")

ratio <- paste0(acNumAgreesRatio$category, "\n","(",round(acNumAgreesRatio$ratio,4)*100, "%",")")
fig4 <- acNumAgreesRatio %>% ggpie("ratio", 
                                     label = ratio, 
                                     fill = "category", 
                                     font.family = font,
                                     color = "white",
                                     lab.pos ="in",
                                     lab.font = c("black"), 
                                     palette = c("#00bfff", "#33e2f6", "#92ffe4", "#adec7d", "#ffbf00")) +
                               theme(legend.text= element_text(size=12), legend.position = "right",legend.direction = "vertical")

ggarrange(fig3, fig4, labels = c("before covid 19", "after covid 19"), hjust = c(-2.9,-2.1), vjust = 3) %>% 
  annotate_figure(top=text_grob("코로나 전후 청원 참여인원수 상위 5개 카테고리 비율", face="bold", family=font, size=24))
```

## 자영업 키워드로 검색한 데이터
